//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorePhone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Specification = new HashSet<Specification>();
        }
    
        public int ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Client { get; set; }
        public int Employee { get; set; }
        public string FormOfPayment { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<Specification> Specification { get; set; }
    }
}
