//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorePhone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public int OrderId { get; set; }
        public int ModelId { get; set; }
        public int Count { get; set; }
        public double PriceModel { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Order Order { get; set; }
    }
}
