//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorePhone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorePhoneEntities : DbContext
    {
        public StorePhoneEntities()
            : base("name=StorePhoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Model> Model { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Producer> Producer { get; set; }
        public DbSet<Specification> Specification { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
